language: ruby

sudo: required
addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 about:blank &

cache:
  bundler: true

matrix:
  fast_finish: true

  include:
    - gemfile: gemfiles/rails_5_1_opal_master.gemfile
      rvm: 2.5.5
    - gemfile: gemfiles/rails_5_2_opal_master.gemfile
      rvm: 2.6.3

    - gemfile: gemfiles/rails_5_1_opal_1_0.gemfile
      rvm: 2.5.5
    - gemfile: gemfiles/rails_5_2_opal_1_0.gemfile
      rvm: 2.6.3

  allow_failures:
    - gemfile: gemfiles/rails_5_1_opal_master.gemfile
      rvm: 2.5.5
    - gemfile: gemfiles/rails_5_2_opal_master.gemfile
      rvm: 2.6.3

before_script: bundle install
script: "bundle exec rake"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

