language: ruby

sudo: false

cache:
  bundler: true

rvm:
  - 2.3.2
  - 2.2.4
  - 2.1.10
  - 2.0.0

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "gem install appraisal"
  - "appraisal install"

script: "appraisal rake"

notifications:
  irc: "irc.freenode.org#opal"

